source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Asset template engines
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

group :development do
	gem 'rspec-rails', '2.6.1'
#	gem 'composite_primary_keys', '=3.1.0'
  gem 'annotate', :git => 'git://github.com/jeremyolliver/annotate_models.git', :branch => 'rake_compatibility'
  gem 'faker'

end
group :test do
	gem 'rspec', '2.6.0'
#	gem 'webrat', '0.7.3'
	gem 'spork', '0.8.5'
	gem 'factory_girl_rails', '1.0'
	gem 'shoulda', '2.11.3'
	gem "capybara"
	gem "guard-rspec"
  gem 'annotate', :git => 'git://github.com/jeremyolliver/annotate_models.git', :branch => 'rake_compatibility'
end


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

